# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_observed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('contributors_enabled', models.NullBooleanField()),
                ('created_at', models.DateTimeField(null=True)),
                ('default_profile', models.NullBooleanField()),
                ('default_profile_image', models.NullBooleanField()),
                ('description', models.TextField(null=True)),
                ('favourites_count', models.IntegerField(null=True)),
                ('followers_count', models.IntegerField(null=True)),
                ('friends_count', models.IntegerField(null=True)),
                ('geo_enabled', models.NullBooleanField()),
                ('has_extended_profile', models.NullBooleanField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_translation_enabled', models.NullBooleanField()),
                ('is_translator', models.NullBooleanField()),
                ('lang', models.CharField(max_length=200, null=True)),
                ('listed_count', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('needs_phone_verification', models.NullBooleanField()),
                ('notifications', models.NullBooleanField()),
                ('profile_background_color', models.CharField(max_length=200, null=True)),
                ('profile_background_image_url', models.CharField(max_length=200, null=True)),
                ('profile_background_image_url_https', models.CharField(max_length=200, null=True)),
                ('profile_background_tile', models.NullBooleanField()),
                ('profile_image_url', models.CharField(max_length=200, null=True)),
                ('profile_image_url_https', models.CharField(max_length=200, null=True)),
                ('profile_link_color', models.CharField(max_length=200, null=True)),
                ('profile_location', models.CharField(max_length=200, null=True)),
                ('profile_sidebar_border_color', models.CharField(max_length=200, null=True)),
                ('profile_sidebar_fill_color', models.CharField(max_length=200, null=True)),
                ('profile_text_color', models.CharField(max_length=200, null=True)),
                ('profile_use_background_image', models.NullBooleanField()),
                ('protected', models.NullBooleanField()),
                ('screen_name', models.CharField(max_length=200, null=True)),
                ('statuses_count', models.IntegerField(null=True)),
                ('suspended', models.NullBooleanField()),
                ('time_zone', models.CharField(max_length=200, null=True)),
                ('translator_type', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('utc_offset', models.CharField(max_length=200, null=True)),
                ('verified', models.NullBooleanField()),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='relo',
            name='sourceuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='streamcollect.User'),
        ),
        migrations.AddField(
            model_name='relo',
            name='targetuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='streamcollect.User'),
        ),
    ]
