# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('contributors_enabled', models.NullBooleanField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('default_profile', models.NullBooleanField()),
                ('default_profile_image', models.NullBooleanField()),
                ('description', models.TextField()),
                ('favourites_count', models.IntegerField(null=True)),
                ('followers_count', models.IntegerField(null=True)),
                ('friends_count', models.IntegerField(null=True)),
                ('geo_enabled', models.NullBooleanField()),
                ('has_extended_profile', models.NullBooleanField()),
                ('id_str', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('is_translation_enabled', models.NullBooleanField()),
                ('is_translator', models.NullBooleanField()),
                ('lang', models.CharField(max_length=200)),
                ('listed_count', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('needs_phone_verification', models.NullBooleanField()),
                ('notifications', models.NullBooleanField()),
                ('profile_background_color', models.CharField(max_length=200)),
                ('profile_background_image_url', models.CharField(max_length=200)),
                ('profile_background_image_url_https', models.CharField(max_length=200)),
                ('profile_background_tile', models.NullBooleanField()),
                ('profile_image_url', models.CharField(max_length=200)),
                ('profile_image_url_https', models.CharField(max_length=200)),
                ('profile_link_color', models.CharField(max_length=200)),
                ('profile_location', models.CharField(max_length=200)),
                ('profile_sidebar_border_color', models.CharField(max_length=200)),
                ('profile_sidebar_fill_color', models.CharField(max_length=200)),
                ('profile_text_color', models.CharField(max_length=200)),
                ('profile_use_background_image', models.NullBooleanField()),
                ('protected', models.NullBooleanField()),
                ('screen_name', models.CharField(max_length=200)),
                ('statuses_count', models.IntegerField(null=True)),
                ('suspended', models.NullBooleanField()),
                ('time_zone', models.CharField(max_length=200)),
                ('translator_type', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('utc_offset', models.CharField(max_length=200)),
                ('verified', models.NullBooleanField()),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
