# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceuser', models.IntegerField()),
                ('targetuser', models.IntegerField()),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_observed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('contributors_enabled', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('default_profile', models.BooleanField()),
                ('default_profile_image', models.BooleanField()),
                ('description', models.TextField()),
                ('favourites_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('friends_count', models.IntegerField()),
                ('geo_enabled', models.BooleanField()),
                ('has_extended_profile', models.BooleanField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_translation_enabled', models.BooleanField()),
                ('is_translator', models.BooleanField()),
                ('lang', models.CharField(max_length=200)),
                ('listed_count', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('needs_phone_verification', models.BooleanField()),
                ('notifications', models.BooleanField()),
                ('profile_background_color', models.CharField(max_length=200)),
                ('profile_background_image_url', models.CharField(max_length=200)),
                ('profile_background_image_url_https', models.CharField(max_length=200)),
                ('profile_background_tile', models.BooleanField()),
                ('profile_image_url', models.CharField(max_length=200)),
                ('profile_image_url_https', models.CharField(max_length=200)),
                ('profile_link_color', models.CharField(max_length=200)),
                ('profile_location', models.CharField(max_length=200, null=True)),
                ('profile_sidebar_border_color', models.CharField(max_length=200)),
                ('profile_sidebar_fill_color', models.CharField(max_length=200)),
                ('profile_text_color', models.CharField(max_length=200)),
                ('profile_use_background_image', models.BooleanField()),
                ('protected', models.BooleanField()),
                ('screen_name', models.CharField(max_length=200)),
                ('statuses_count', models.IntegerField()),
                ('suspended', models.BooleanField()),
                ('time_zone', models.CharField(max_length=200, null=True)),
                ('translator_type', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200, null=True)),
                ('utc_offset', models.CharField(max_length=200, null=True)),
                ('verified', models.BooleanField()),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
