# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='streamed',
            field=models.BooleanField(default=0),
        ),
    ]
