# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0002_tweet_streamed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
