# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0003_user_relevant_in_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relo',
            old_name='observed_at',
            new_name='observed_att',
        ),
    ]
