# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0003_auto_20170831_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='relo',
            name='observed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='relo',
            name='source_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relo_out', to='streamcollect.User'),
        ),
        migrations.AlterField(
            model_name='relo',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relo_in', to='streamcollect.User'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet', to='streamcollect.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='added_at',
            field=models.DateTimeField(),
        ),
    ]
