# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0003_accesstoken_screen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.IntegerField(),
        ),
    ]
