# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0004_auto_20170909_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
