# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0005_keyword_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='streamed',
        ),
        migrations.AddField(
            model_name='tweet',
            name='data_source',
            field=models.IntegerField(default=0),
        ),
    ]
