# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0005_auto_20170602_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contributors_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_translator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notifications',
        ),
    ]
