# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0006_auto_20170909_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_source',
            field=models.IntegerField(default=0),
        ),
    ]
