# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0006_auto_20170607_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='relevant_in_degree',
            new_name='in_degree',
        ),
        migrations.AddField(
            model_name='user',
            name='out_degree',
            field=models.IntegerField(default=0),
        ),
    ]
