# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0007_user_data_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lat_1', models.FloatField(null=True)),
                ('lat_2', models.FloatField(null=True)),
                ('long_1', models.FloatField(null=True)),
                ('long_2', models.FloatField(null=True)),
                ('time_start', models.DateTimeField(null=True)),
                ('time_end', models.DateTimeField(null=True)),
                ('kw_stream_start', models.DateTimeField(null=True)),
                ('gps_stream_start', models.DateTimeField(null=True)),
            ],
        ),
    ]
