# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0007_auto_20170619_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(max_length=40, unique=True)),
                ('is_gps', models.BooleanField()),
            ],
        ),
    ]
