# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0008_celerystream'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_class',
            field=models.IntegerField(default=0),
        ),
    ]
