# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0009_auto_20170926_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gps_stream_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='kw_stream_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
