# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0009_user_user_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(max_length=40, unique=True)),
                ('task_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='CeleryStream',
        ),
    ]
