# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0011_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('access_key_tw', models.CharField(max_length=100)),
                ('access_secret_tw', models.CharField(max_length=100)),
            ],
        ),
    ]
