# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0012_remove_keyword_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword', to='streamcollect.Event'),
        ),
    ]
