# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0013_remove_accesstoken_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='access_key_tw',
        ),
        migrations.RemoveField(
            model_name='accesstoken',
            name='access_secret_tw',
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='access_key',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='access_secret',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
