# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0014_auto_20170926_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='geopoint',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geopoint',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
