# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0014_auto_20170627_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=100, unique=True)),
                ('consumer_secret', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
