# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0015_consumerkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('coordinates_lat', models.FloatField(null=True)),
                ('coordinates_long', models.FloatField(null=True)),
                ('coordinates_type', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField()),
                ('favorite_count', models.IntegerField()),
                ('filter_level', models.CharField(max_length=10)),
                ('tweet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('in_reply_to_status_id', models.IntegerField(null=True)),
                ('in_reply_to_user_id', models.IntegerField(null=True)),
                ('lang', models.CharField(max_length=10)),
                ('possibly_sensitive', models.NullBooleanField()),
                ('quoted_status_id', models.IntegerField(null=True)),
                ('retweet_count', models.IntegerField()),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('tweets', models.ManyToManyField(to='streamcollect.Tweet')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_background_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_background_image_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_background_image_url_https',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_background_tile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image_url_https',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_link_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_sidebar_border_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_sidebar_fill_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_text_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_use_background_image',
        ),
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='streamcollect.User'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='tweets',
            field=models.ManyToManyField(to='streamcollect.Tweet'),
        ),
    ]
