# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0016_auto_20170716_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='filter_level',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='possibly_sensitive',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='lang',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
