# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-19 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0017_auto_20180319_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='data_code',
        ),
        migrations.AddField(
            model_name='data_code',
            name='tweets',
            field=models.ManyToManyField(to='streamcollect.Tweet'),
        ),
    ]
