# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-20 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0018_auto_20180319_2357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data_Code',
            new_name='DataCode',
        ),
    ]
