# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-20 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0019_auto_20180320_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacode',
            name='tweets',
        ),
    ]
