# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-20 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0020_remove_datacode_tweets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coder_id', models.IntegerField(default=1)),
                ('data_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamcollect.DataCode')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamcollect.Tweet')),
            ],
        ),
        migrations.AddField(
            model_name='datacode',
            name='tweets',
            field=models.ManyToManyField(through='streamcollect.Coder', to='streamcollect.Tweet'),
        ),
    ]
