# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-12 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0022_datacode_data_code_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCodeDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
