# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-13 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0024_datacode_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacode',
            name='dimension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datacode', to='streamcollect.DataCodeDimension'),
        ),
    ]
