# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-28 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0026_auto_20180419_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coder',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coder', to='streamcollect.Tweet'),
        ),
    ]
