# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-31 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0027_auto_20180528_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coder',
            new_name='Coding',
        )
    ]
