# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-01 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0030_datacodedimension_coding_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_screen_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
