# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-01 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0031_user_new_screen_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place_id', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=200, null=True)),
                ('place_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=100)),
                ('lat_1', models.FloatField(null=True)),
                ('lon_1', models.FloatField(null=True)),
                ('lat_2', models.FloatField(null=True)),
                ('lon_2', models.FloatField(null=True)),
                ('lat_3', models.FloatField(null=True)),
                ('lon_3', models.FloatField(null=True)),
                ('lat_4', models.FloatField(null=True)),
                ('lon_4', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tweet', to='streamcollect.Place'),
        ),
    ]
