# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-08 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0033_auto_20180908_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='is_deleted',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.NullBooleanField(),
        ),
    ]
