# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-10 23:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0034_auto_20180908_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='media_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.AddField(
            model_name='tweet',
            name='media_files_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='tweets',
            field=models.ManyToManyField(related_name='hashtags', to='streamcollect.Tweet'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='tweets',
            field=models.ManyToManyField(related_name='mentions', to='streamcollect.Tweet'),
        ),
        migrations.AlterField(
            model_name='url',
            name='tweets',
            field=models.ManyToManyField(related_name='urls', to='streamcollect.Tweet'),
        ),
    ]
