# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0035_auto_20180910_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_quoted',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='tweet',
            name='is_replied_to',
            field=models.NullBooleanField(),
        ),
    ]
