# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-12 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0036_auto_20180912_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='quoted_status_id',
            new_name='quoted_status_id_int',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='is_quoted',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='is_replied_to',
        ),
        migrations.AddField(
            model_name='tweet',
            name='quoted_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_by', to='streamcollect.Tweet'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='replied_to_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_by', to='streamcollect.Tweet'),
        ),
    ]
