# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-12 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0037_auto_20180912_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
