# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-12 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0038_auto_20180912_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='country_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
