# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-12 19:52
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0039_auto_20180912_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_followers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='user_following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
