# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-12 19:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0040_auto_20180912_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_followers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), null=True, size=None),
        ),
    ]
