# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-24 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0042_auto_20181009_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='betweenness_centrality',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='closeness_centrality',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='degree_centrality',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='eigenvector_centrality',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='katz_centrality',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='load_centrality',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='undirected_eigenvector_centrality',
            field=models.FloatField(null=True),
        ),
    ]
