# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-26 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0043_auto_20190424_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ratio_detected',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ratio_media',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ratio_original',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tweets_per_hour',
            field=models.FloatField(null=True),
        ),
    ]
