# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-28 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamcollect', '0045_remove_user_suspended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='betweenness_centrality',
            new_name='centrality_betweenness',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='closeness_centrality',
            new_name='centrality_closeness',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='degree_centrality',
            new_name='centrality_degree',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='eigenvector_centrality',
            new_name='centrality_eigenvector',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='katz_centrality',
            new_name='centrality_katz',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='load_centrality',
            new_name='centrality_load',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='undirected_eigenvector_centrality',
            new_name='centrality_undirected_eigenvector',
        ),
    ]
